"""
Hypertext markup language render engine.

NOT an admitted unary callable. This is an external tool invoked by
the admitted process.py wrapper. It performs multi-step ontology
querying and text generation that cannot be compressed into a single
atomic byte-frame arrow.

Type carriers (primordial):
  - Input  : prim:ByteVector  (turtle ontology from SILMARIL_ONTOLOGY_PATH)
  - Output : prim:ByteVector  (generated HTML written to stdout)
  - Effect : prim:IOException ∪ prim:SPARQLSyntaxError
"""

import os

from config.constants.morphism.user.interface.constructor.hypertext.markup.language.render.format.value import VALUE as _FORMAT
from config.gate.external.python.resource_description_framework_library.graph.library import DEPENDENCY as _GRAPH


def MAIN() -> int:
    ontology_path = os.environ.get("SILMARIL_ONTOLOGY_PATH", "basicttl/ui_constructor.ttl")

    g = _GRAPH()
    g.parse(ontology_path, format=_FORMAT.decode())

    NS = "urn:silmaril:entity#"

    out = []
    out.append("<!-- Generated by silmaril.sparky.morphism.user.interface.constructor.hypertext.markup.language.render.engine -->")
    out.append("<!-- Source: basicttl/ui_constructor.ttl -->")
    out.append("")
    out.append('<div class="build-status-bar">')

    # Extract build status definitions
    q = """
        PREFIX silm: <urn:silmaril:entity#>
        SELECT ?status ?label ?title WHERE {
            ?s a silm:BuildStatusDefinition .
            ?s silm:statusClass ?status .
            ?s silm:label ?label .
            ?s silm:title ?title .
        }
        ORDER BY ?status
    """

    for row in g.query(q):
        status = str(row.status)
        label = str(row.label)
        title = str(row.title)

        # Find SVG primitive for this status
        pq = f"""
            PREFIX silm: <urn:silmaril:entity#>
            SELECT ?primitive WHERE {{
                ?p a silm:SVGPrimitive ;
                   silm:iconForStatus "{status}" .
                ?p a ?primitive .
            }}
        """
        primitive = None
        for prow in g.query(pq):
            ptype = str(prow.primitive)
            if "SVGPolyline" in ptype:
                primitive = "polyline"
            elif "SVGLine" in ptype:
                primitive = "line"
            elif "SVGPolygon" in ptype:
                primitive = "polygon"
            elif "SVGCircle" in ptype:
                primitive = "circle"

        if primitive == "polyline":
            # Get points
            ptq = f"""
                PREFIX silm: <urn:silmaril:entity#>
                SELECT ?x ?y WHERE {{
                    ?p a silm:SVGPrimitive ;
                       silm:iconForStatus "{status}" ;
                       silm:hasPoint ?pt .
                    ?pt silm:x ?x ;
                        silm:y ?y .
                }}
                ORDER BY ?pt
            """
            points = []
            for ptrow in g.query(ptq):
                points.append(f"{ptrow.x},{ptrow.y}")
            pts = " ".join(points)
            svg = f'<polyline points="{pts}"/>'
        elif primitive == "line":
            ptq = f"""
                PREFIX silm: <urn:silmaril:entity#>
                SELECT ?x1 ?y1 ?x2 ?y2 WHERE {{
                    ?p a silm:SVGPrimitive ;
                       silm:iconForStatus "{status}" ;
                       silm:x1 ?x1 ;
                       silm:y1 ?y1 ;
                       silm:x2 ?x2 ;
                       silm:y2 ?y2 .
                }}
            """
            svg = ""
            for ptrow in g.query(ptq):
                svg += f'<line x1="{ptrow.x1}" y1="{ptrow.y1}" x2="{ptrow.x2}" y2="{ptrow.y2}"/>'
        elif primitive == "polygon":
            ptq = f"""
                PREFIX silm: <urn:silmaril:entity#>
                SELECT ?x ?y WHERE {{
                    ?p a silm:SVGPrimitive ;
                       silm:iconForStatus "{status}" ;
                       silm:hasPoint ?pt .
                    ?pt silm:x ?x ;
                        silm:y ?y .
                }}
                ORDER BY ?pt
            """
            points = []
            for ptrow in g.query(ptq):
                points.append(f"{ptrow.x},{ptrow.y}")
            pts = " ".join(points)
            svg = f'<polygon points="{pts}"/>'
        elif primitive == "circle":
            ptq = f"""
                PREFIX silm: <urn:silmaril:entity#>
                SELECT ?cx ?cy ?r WHERE {{
                    ?p a silm:SVGPrimitive ;
                       silm:iconForStatus "{status}" ;
                       silm:cx ?cx ;
                       silm:cy ?cy ;
                       silm:r ?r .
                }}
            """
            svg = ""
            for ptrow in g.query(ptq):
                svg = f'<circle cx="{ptrow.cx}" cy="{ptrow.cy}" r="{ptrow.r}"/>'
        else:
            svg = ""

        if svg:
            svg_wrapper = f'<svg class="status-icon" aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{svg}</svg>'
        else:
            svg_wrapper = ""

        out.append(f'    <span class="build-status {status}" title="{title}">')
        if svg_wrapper:
            out.append(f"        {svg_wrapper}")
        out.append(f"        {label}")
        out.append("    </span>")

    out.append("</div>")

    print("\n".join(out))
    return 0


raise SystemExit(MAIN())
