from config.constants.morphism.codebase.volume.executable.rg.value import VALUE as RG


VALUE = (
    RG,
    "--sort",
    "path",
    "--hidden",
    "--line-number",
    "--glob",
    "!.git/**",
    "--glob",
    "lib/telephone/application.ex",
    "--glob",
    "lib/telephone/application/*.ex",
    "--glob",
    "lib/telephone/kernel/supervisor.ex",
    "--glob",
    "lib/research/render/telephone/switchboard/**/*.ex",
    "--glob",
    "lib/research/render/config/telephone/l1/**/*.ex",
    "--glob",
    "lib/research/render/lambda/writer/format/structured/file/object/container/avro/**/*.ex",
    "--glob",
    "config/constants/telephone/l1/switchboard.exs",
    "--glob",
    "config/constants/telephone/lambda/writer/format/structured/file/object/container/avro.exs",
    "--glob",
    "config/constants/native/executor/io/uring.exs",
    "--glob",
    "native/telephone/native/src/executor/iouring/executor.cpp",
    "^",
    ".",
)
