VALUE = (
    "python3",
    "-c",
    r'''import sys

count = open(sys.argv[2], encoding="utf-8").read().rstrip("\n")
statements = open(sys.argv[3], encoding="utf-8").read().rstrip("\n")
entities = open(sys.argv[4], encoding="utf-8").read().rstrip("\n")
sys.stdout.write(sys.argv[1].format(count, statements, entities))
''',
    r'''# Silmaril Ontology Manifest
# Generated by consolidate-ontology.py

@prefix silm: <urn:silmaril:entity#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix void: <http://rdfs.org/ns/void#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

silm:OntologyManifest a owl:Ontology ;
    rdfs:label "Silmaril Consolidated Ontology" ;
    rdfs:comment "Consolidated from {0} source TTL files" ;
    owl:versionInfo "1.0.0" .

silm:ConsolidatedGraph a void:Dataset ;
    rdfs:label "Silmaril Knowledge Graph" ;
    void:triples "{1}"^^xsd:integer ;
    void:entities "{2}"^^xsd:integer .
''',
)
