.PHONY: morphism-contract-validation-mechanic-artifact-kind
morphism-contract-validation-mechanic-artifact-kind: $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/output.bin $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/effect.bin

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/source.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/artifact/kind/source/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/closed-enumeration.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-kind.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-identity.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-path.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-schema.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-status.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-source-evidence.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/document-schema.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/schema-document-schema.frame
	@mkdir -p "$(@D)"
	@set +e; cat "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/closed-enumeration.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-kind.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-identity.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-path.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-schema.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-status.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/registration-source-evidence.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/document-schema.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/schema-document-schema.frame" | PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.artifact.kind.source.process >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/accepted.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/artifact/kind/classification/accepted/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/source.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.artifact.kind.classification.accepted.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/source.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/decode_failure.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/artifact/kind/classification/decode_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/accepted.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.artifact.kind.classification.decode_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/accepted.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/parse_failure.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/artifact/kind/classification/parse_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/decode_failure.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.artifact.kind.classification.parse_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/decode_failure.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/artifact/kind/classification/rejected/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/parse_failure.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.artifact.kind.classification.rejected.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification/parse_failure.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/output.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/artifact/kind/output/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.artifact.kind.output.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/effect.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/artifact/kind/effect/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.artifact.kind.effect.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/artifact/kind/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"


.PHONY: morphism-contract-validation-mechanic-digest-support
morphism-contract-validation-mechanic-digest-support: $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/output.bin $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/effect.bin

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/source.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/digest/support/source/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/coordinate.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/value.frame
	@mkdir -p "$(@D)"
	@set +e; cat "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/coordinate.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/value.frame" | PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.digest.support.source.process >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/accepted.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/digest/support/classification/accepted/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/source.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.digest.support.classification.accepted.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/source.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/decode_failure.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/digest/support/classification/decode_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/accepted.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.digest.support.classification.decode_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/accepted.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/parse_failure.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/digest/support/classification/parse_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/decode_failure.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.digest.support.classification.parse_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/decode_failure.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/digest/support/classification/rejected/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/parse_failure.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.digest.support.classification.rejected.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification/parse_failure.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/output.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/digest/support/output/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.digest.support.output.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/effect.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/digest/support/effect/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.digest.support.effect.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/digest/support/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"


.PHONY: morphism-contract-validation-mechanic-format
morphism-contract-validation-mechanic-format: $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/output.bin $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/effect.bin

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/source.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/format/source/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/name.frame $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/value.frame
	@mkdir -p "$(@D)"
	@set +e; cat "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/name.frame" "$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/value.frame" | PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.format.source.process >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/accepted.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/format/classification/accepted/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/source.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.format.classification.accepted.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/source.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/decode_failure.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/format/classification/decode_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/accepted.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.format.classification.decode_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/accepted.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/parse_failure.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/format/classification/parse_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/decode_failure.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.format.classification.parse_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/decode_failure.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/format/classification/rejected/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/parse_failure.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.format.classification.rejected.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification/parse_failure.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/output.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/format/output/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.format.output.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/effect.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/format/effect/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.format.effect.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/format/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"


.PHONY: morphism-contract-validation-mechanic-json
morphism-contract-validation-mechanic-json: $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/output.bin $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/effect.bin

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/accepted.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/json/classification/accepted/process.py $(MCV_JSON_VALUE)
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.json.classification.accepted.process <"$(MCV_JSON_VALUE)" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/rejected.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/json/classification/rejected/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/accepted.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.json.classification.rejected.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/accepted.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/decode_failure.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/json/classification/decode_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/rejected.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.json.classification.decode_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/rejected.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/json/classification/parse_failure/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/decode_failure.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.json.classification.parse_failure.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification/decode_failure.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/output.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/json/output/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.json.output.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"

$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/effect.bin: $(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)/silmaril/sparky/morphism/contract/validation/mechanic/json/effect/process.py $(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification.bin
	@mkdir -p "$(@D)"
	@set +e; PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="$(MORPHISM_CONTRACT_VALIDATION_SOURCE_ROOT)" "$(SILMARIL_PYTHON)" -m silmaril.sparky.morphism.contract.validation.mechanic.json.effect.process <"$(MORPHISM_CONTRACT_VALIDATION_ARTIFACT_ROOT)/mechanic/json/classification.bin" >"$@.pending" 2>"$@.stderr"; STATUS=$$?; printf '%s\n' "$$STATUS" >"$@.status"; set -e; if [ "$$STATUS" -ne 0 ]; then cat "$@.stderr" >&2; exit "$$STATUS"; fi; mv "$@.pending" "$@"
