VALUE = (
    "overload_identity",
    "rejected_event",
    "overload_identity",
    "rejected_handle",
    "overload_identity",
    "absent_token",
    "commit_lag_bound",
    "lag_max",
    "commit_group_bound",
    "group_batch_max",
    "iouring_queue_bound",
    "queue_entries",
    "grouped_sqe",
    "IORING_OP_WRITEV",
    "grouped_sqe",
    "active_submission.assign(chunks)",
    "grouped_sqe",
    "sqe->len",
    "backend_selection",
    "native_append_mode",
    "backend_selection",
    "fallback: :writev",
)
