LAMBDA_BLOTTO_DIRECTORY_OUTPUT ?= $(CURDIR)/build/lambda_blotto/directory
LAMBDA_BLOTTO_DIRECTORY_PRE := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/metadata.pre
LAMBDA_BLOTTO_DIRECTORY_NAMES_RAW := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/names.raw
LAMBDA_BLOTTO_DIRECTORY_NAMES := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/names.sorted
LAMBDA_BLOTTO_DIRECTORY_COUNT := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/count
LAMBDA_BLOTTO_DIRECTORY_BOUND := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/bound
LAMBDA_BLOTTO_DIRECTORY_PAYLOAD := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/payload.tar
LAMBDA_BLOTTO_DIRECTORY_POST := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/metadata.post
LAMBDA_BLOTTO_DIRECTORY_STABILITY := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/stability
LAMBDA_BLOTTO_DIRECTORY_EVIDENCE := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/evidence
LAMBDA_BLOTTO_DIRECTORY_RECEIPT := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/receipt.tar
LAMBDA_BLOTTO_DIRECTORY_DIGEST := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/receipt.sha256
LAMBDA_BLOTTO_DIRECTORY_READBACK := $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)/readback

.PHONY: lambda-blotto-directory-capture
lambda-blotto-directory-capture: $(LAMBDA_BLOTTO_DIRECTORY_READBACK)

$(LAMBDA_BLOTTO_DIRECTORY_OUTPUT):
	mkdir -p "$@"

$(LAMBDA_BLOTTO_DIRECTORY_PRE): | $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)
	stat --dereference --printf='%d\n%i\n%f\n%h\n%u\n%g\n%s\n%Y\n%Z\n' "$(LAMBDA_BLOTTO_DIRECTORY_SOURCE)" >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_NAMES_RAW): $(LAMBDA_BLOTTO_DIRECTORY_PRE)
	find -P "$(LAMBDA_BLOTTO_DIRECTORY_SOURCE)" -mindepth 1 -maxdepth 1 -printf '%f\0' >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_NAMES): $(LAMBDA_BLOTTO_DIRECTORY_NAMES_RAW)
	sort --zero-terminated "$<" >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_COUNT): $(LAMBDA_BLOTTO_DIRECTORY_NAMES)
	awk -v RS='\0' 'END { print NR }' "$<" >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_BOUND): $(LAMBDA_BLOTTO_DIRECTORY_COUNT)
	awk -v maximum="$(LAMBDA_BLOTTO_DIRECTORY_MAXIMUM_ENTRIES)" '$$1 <= maximum { accepted = 1 } END { if (!accepted) { print "directory_capture_maximum_entries_exceeded" > "/dev/stderr"; exit 65 } }' "$<" >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_PAYLOAD): $(LAMBDA_BLOTTO_DIRECTORY_BOUND)
	tar --format=posix --create --file="$@" --directory="$(dir $(LAMBDA_BLOTTO_DIRECTORY_SOURCE))" "$(notdir $(LAMBDA_BLOTTO_DIRECTORY_SOURCE))"

$(LAMBDA_BLOTTO_DIRECTORY_POST): $(LAMBDA_BLOTTO_DIRECTORY_PAYLOAD)
	stat --dereference --printf='%d\n%i\n%f\n%h\n%u\n%g\n%s\n%Y\n%Z\n' "$(LAMBDA_BLOTTO_DIRECTORY_SOURCE)" >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_STABILITY): $(LAMBDA_BLOTTO_DIRECTORY_PRE) $(LAMBDA_BLOTTO_DIRECTORY_POST)
	cmp --silent "$(LAMBDA_BLOTTO_DIRECTORY_PRE)" "$(LAMBDA_BLOTTO_DIRECTORY_POST)" >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_EVIDENCE): | $(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)
	awk -v evidence="$(LAMBDA_BLOTTO_EVIDENCE_CLASS)" 'BEGIN { if (evidence != "observed") { print "non_observed_directory_capture_rejected" > "/dev/stderr"; exit 65 } }' >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_RECEIPT): $(LAMBDA_BLOTTO_DIRECTORY_NAMES) $(LAMBDA_BLOTTO_DIRECTORY_PAYLOAD) $(LAMBDA_BLOTTO_DIRECTORY_POST) $(LAMBDA_BLOTTO_DIRECTORY_STABILITY) $(LAMBDA_BLOTTO_DIRECTORY_EVIDENCE)
	tar --format=posix --create --file="$@" --directory="$(LAMBDA_BLOTTO_DIRECTORY_OUTPUT)" metadata.pre metadata.post names.sorted payload.tar stability evidence --directory="$(CURDIR)" phoenix-disintegration-routing.json federated-computing-substrate-routing.json

$(LAMBDA_BLOTTO_DIRECTORY_DIGEST): $(LAMBDA_BLOTTO_DIRECTORY_RECEIPT)
	sha256sum "$<" >"$@"

$(LAMBDA_BLOTTO_DIRECTORY_READBACK): $(LAMBDA_BLOTTO_DIRECTORY_DIGEST)
	sha256sum --check "$<" >"$@"
