# Canonical, fail-closed bindings for the real Volume 40 publication handoff.
# Callers must name every environment-owned coordinate.  No host path, live
# evidence source, Python interpreter, or final-working root is guessed here.

VOLUME_40_CONTRACT_ROOT := $(CURDIR)/make/morphism/codebase/volume/40/contract
VOLUME_40_INVENTORY_CONTRACT := $(VOLUME_40_CONTRACT_ROOT)/inventory.csv
VOLUME_40_INSTALL_PATH_CONTRACT := $(VOLUME_40_CONTRACT_ROOT)/install.paths
VOLUME_40_PROJECTION_CONTRACT_ROOT := $(VOLUME_40_CONTRACT_ROOT)/projection

VOLUME_40_BUILD_ROOT ?= $(CURDIR)/build/morphism/codebase/volume/40
VOLUME_40_PRODUCTION_ROOT ?= $(VOLUME_40_BUILD_ROOT)/production/generated
VOLUME_40_RECEIPT_ROOT ?= $(VOLUME_40_BUILD_ROOT)/receipts
VOLUME_40_HASH_ROOT ?= $(VOLUME_40_BUILD_ROOT)/hash
VOLUME_40_INSTALL_STAGE_ROOT ?= $(VOLUME_40_BUILD_ROOT)/install-stage/generated
VOLUME_40_INSTALL_RECEIPT_ROOT ?= $(VOLUME_40_BUILD_ROOT)/install-receipts
VOLUME_40_READBACK_ROOT ?= $(VOLUME_40_BUILD_ROOT)/readback

VOLUME_40_SOURCE_ROOT ?=
VOLUME_40_CATALOG_REPOSITORY ?=
VOLUME_40_FINAL_WORKING_ROOT ?=
VOLUME_40_TELEPHONE_QUERY ?=
VOLUME_40_PHASE14_QUERY_TIER ?=
VOLUME_40_PHASE14_FRAME_HEAD ?=
VOLUME_40_PHASE14_QUERY_SCOPE ?=
VOLUME_40_PHASE14_SOURCE ?= telephone
VOLUME_40_PHASE14_L1_OK_GLOB ?=
VOLUME_40_PHASE14_L1_ERROR_GLOB ?=
VOLUME_40_PHASE14_CELL_COUNT ?= 104
VOLUME_40_SOURCE_FILES_ROW_FILES ?=
VOLUME_40_GDB_EVIDENCE_ROW_FILES ?=
VOLUME_40_RING_FAMILIES_ROW_FILES ?=
VOLUME_40_SHARED_COMPONENTS_ROW_FILES ?=
VOLUME_40_SHARED_ANCHORS_ROW_FILES ?=
VOLUME_40_STRICT_SOURCE_BODY_RECEIPT ?= $(VOLUME_SOURCE_BODY_RECEIPT)
VOLUME_40_STRICT_SOURCE_BODY_TOKEN ?= source_body_total_application=verified

VOLUME_40_FINAL_GENERATED_RELATIVE := src/volumes/40_silmaril_wire_codebase/generated
VOLUME_40_FINAL_GENERATED_ROOT = $(VOLUME_40_FINAL_WORKING_ROOT)/$(VOLUME_40_FINAL_GENERATED_RELATIVE)
VOLUME_40_PROJECTION_ARTIFACT_PREFIX := $(VOLUME_40_FINAL_GENERATED_RELATIVE)/

SILMARIL_PYLIB_SOURCE_ROOT ?= $(CURDIR)/src
MORPHISM_CODEBASE_VOLUME_SOURCE_ROOT := $(CURDIR)/src
MORPHISM_CODEBASE_VOLUME_OPERATION_ROOT := $(VOLUME_40_BUILD_ROOT)/operation
MORPHISM_CODEBASE_VOLUME_OBSERVATION_SOURCE_ROOT = $(VOLUME_40_SOURCE_ROOT)
MORPHISM_CODEBASE_VOLUME_TABLE_ARTIFACT_ROOT := $(VOLUME_40_BUILD_ROOT)/table
MORPHISM_CODEBASE_VOLUME_TABLE_CONSTRUCT_ROOT := $(VOLUME_40_BUILD_ROOT)/table/construct

VOLUME_REPOSITORY = $(VOLUME_40_CATALOG_REPOSITORY)
VOLUME_INVENTORY_CATALOG_DOCUMENTS_OUTPUT_ROOT := $(VOLUME_40_BUILD_ROOT)/inventory/catalog-documents
VOLUME_INVENTORY_CATALOG_CLAIMS_OUTPUT_ROOT := $(VOLUME_40_BUILD_ROOT)/inventory/catalog-claims
VOLUME_INVENTORY_CATALOG_GAPS_OUTPUT_ROOT := $(VOLUME_40_BUILD_ROOT)/inventory/catalog-gaps
VOLUME_INVENTORY_CATALOG_QUALITY_FLAGS_OUTPUT_ROOT := $(VOLUME_40_BUILD_ROOT)/inventory/catalog-quality-flags

VOLUME_TABLE_CONFIGURATION_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_DEPENDENCIES_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_DOCUMENTATION_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_MAKE_TARGETS_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_MIX_TASKS_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_MODULES_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_NATIVE_TREE_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_PROJECT_TASKS_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_PROVENANCE_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_PUBLIC_APIS_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_SCRIPTS_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_TELEPHONE_TOPOLOGY_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)
VOLUME_TABLE_TESTS_INPUT = $(VOLUME_OBSERVATION_LINE_ORDER)

VOLUME_SOURCE_FILES_ROW_FILES = $(VOLUME_40_SOURCE_FILES_ROW_FILES)
VOLUME_GDB_EVIDENCE_ROW_FILES = $(VOLUME_40_GDB_EVIDENCE_ROW_FILES)
VOLUME_RING_FAMILIES_ROW_FILES = $(VOLUME_40_RING_FAMILIES_ROW_FILES)
VOLUME_SHARED_COMPONENTS_ROW_FILES = $(VOLUME_40_SHARED_COMPONENTS_ROW_FILES)
VOLUME_SHARED_ANCHORS_ROW_FILES = $(VOLUME_40_SHARED_ANCHORS_ROW_FILES)

VOLUME_TELEPHONE_QUERY = $(VOLUME_40_TELEPHONE_QUERY)
VOLUME_PHASE14_QUERY_TIER = $(VOLUME_40_PHASE14_QUERY_TIER)
VOLUME_PHASE14_FRAME_HEAD = $(VOLUME_40_PHASE14_FRAME_HEAD)
VOLUME_PHASE14_QUERY_SCOPE = $(VOLUME_40_PHASE14_QUERY_SCOPE)
VOLUME_PHASE14_CELL_COUNT = $(VOLUME_40_PHASE14_CELL_COUNT)
VOLUME_PHASE14_OUTPUT := $(VOLUME_40_BUILD_ROOT)/phase14
VOLUME_PHASE14_TABLE_OUTPUT := $(VOLUME_40_BUILD_ROOT)/table/phase14

VOLUME_PROJECTION_OUTPUT_ROOT = $(VOLUME_40_PRODUCTION_ROOT)
VOLUME_PROJECTION_ARTIFACT_PREFIX = $(VOLUME_40_PROJECTION_ARTIFACT_PREFIX)
VOLUME_PROJECTION_ARCHITECTURE_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/architecture.paths
VOLUME_PROJECTION_BUILD_CONFIGURATION_TASKS_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/build_configuration_tasks.paths
VOLUME_PROJECTION_TELEPHONE_RINGS_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/telephone_rings.paths
VOLUME_PROJECTION_NATIVE_GDB_VERIFICATION_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/native_gdb_verification.paths
VOLUME_PROJECTION_OPERATIONS_DOCUMENTATION_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/operations_documentation.paths
VOLUME_PROJECTION_PROVENANCE_RELATIONS_GAPS_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/provenance_relations_gaps.paths
VOLUME_PROJECTION_PHASE14_26X4_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/phase14_26x4.paths
VOLUME_PROJECTION_VOLUME_BODY_INPUT := $(VOLUME_40_PROJECTION_CONTRACT_ROOT)/body.paths

VOLUME_INVENTORY_CONTRACT = $(VOLUME_40_INVENTORY_CONTRACT)
VOLUME_ARTIFACT_MANIFEST_GENERATED_ROOT = $(VOLUME_40_PRODUCTION_ROOT)
VOLUME_ARTIFACT_MANIFEST_OUTPUT_ROOT := $(VOLUME_40_BUILD_ROOT)/artifact-manifest
VOLUME_ARTIFACT_MANIFEST = $(VOLUME_40_PRODUCTION_ROOT)/manifest.json
VOLUME_SOURCE_TO_FRAGMENT_GENERATED_ROOT = $(VOLUME_40_PRODUCTION_ROOT)
VOLUME_SOURCE_TO_FRAGMENT_OUTPUT_ROOT := $(VOLUME_40_BUILD_ROOT)/source-to-fragment
VOLUME_SOURCE_TO_FRAGMENT = $(VOLUME_40_PRODUCTION_ROOT)/source_to_fragment.csv

.PHONY: volume-40-bindings
volume-40-bindings:
	@test -n "$(SILMARIL_PYTHON)" || { printf '%s\n' 'SILMARIL_PYTHON is required' >&2; exit 64; }
	@test -x "$(SILMARIL_PYTHON)" || { printf 'SILMARIL_PYTHON is not executable: %s\n' "$(SILMARIL_PYTHON)" >&2; exit 66; }
	@test -n "$(VOLUME_40_SOURCE_ROOT)" || { printf '%s\n' 'VOLUME_40_SOURCE_ROOT is required' >&2; exit 64; }
	@test -d "$(VOLUME_40_SOURCE_ROOT)" || { printf 'VOLUME_40_SOURCE_ROOT is not a directory: %s\n' "$(VOLUME_40_SOURCE_ROOT)" >&2; exit 66; }
	@test -n "$(VOLUME_40_CATALOG_REPOSITORY)" || { printf '%s\n' 'VOLUME_40_CATALOG_REPOSITORY is required' >&2; exit 64; }
	@test -f "$(VOLUME_40_CATALOG_REPOSITORY)/library.duckdb" || { printf 'catalog repository omits library.duckdb: %s\n' "$(VOLUME_40_CATALOG_REPOSITORY)" >&2; exit 66; }
	@test -n "$(VOLUME_40_FINAL_WORKING_ROOT)" || { printf '%s\n' 'VOLUME_40_FINAL_WORKING_ROOT is required' >&2; exit 64; }
	@test -d "$(VOLUME_40_FINAL_WORKING_ROOT)" || { printf 'VOLUME_40_FINAL_WORKING_ROOT is not a directory: %s\n' "$(VOLUME_40_FINAL_WORKING_ROOT)" >&2; exit 66; }
	@case "$(VOLUME_40_PHASE14_SOURCE)" in telephone|l1_snapshot) ;; *) printf 'unsupported VOLUME_40_PHASE14_SOURCE: %s\n' "$(VOLUME_40_PHASE14_SOURCE)" >&2; exit 64 ;; esac
	@if test "$(VOLUME_40_PHASE14_SOURCE)" = telephone; then test -n "$(VOLUME_40_TELEPHONE_QUERY)" || { printf '%s\n' 'VOLUME_40_TELEPHONE_QUERY is required' >&2; exit 64; }; test -x "$(VOLUME_40_TELEPHONE_QUERY)" || { printf 'VOLUME_40_TELEPHONE_QUERY is not executable: %s\n' "$(VOLUME_40_TELEPHONE_QUERY)" >&2; exit 66; }; test -n "$(VOLUME_40_PHASE14_QUERY_TIER)" || { printf '%s\n' 'VOLUME_40_PHASE14_QUERY_TIER is required' >&2; exit 64; }; fi
	@if test "$(VOLUME_40_PHASE14_SOURCE)" = telephone && test "$(VOLUME_40_PHASE14_QUERY_TIER)" = L1; then test -n "$(VOLUME_40_PHASE14_FRAME_HEAD)" || { printf '%s\n' 'VOLUME_40_PHASE14_FRAME_HEAD is required for L1' >&2; exit 64; }; fi
	@if test "$(VOLUME_40_PHASE14_SOURCE)" = l1_snapshot; then test -n "$(VOLUME_40_PHASE14_L1_OK_GLOB)" || { printf '%s\n' 'VOLUME_40_PHASE14_L1_OK_GLOB is required for l1_snapshot' >&2; exit 64; }; test -n "$(VOLUME_40_PHASE14_L1_ERROR_GLOB)" || { printf '%s\n' 'VOLUME_40_PHASE14_L1_ERROR_GLOB is required for l1_snapshot' >&2; exit 64; }; fi
	@test -n "$(VOLUME_40_SOURCE_FILES_ROW_FILES)" || { printf '%s\n' 'VOLUME_40_SOURCE_FILES_ROW_FILES is required' >&2; exit 64; }
	@test -n "$(VOLUME_40_GDB_EVIDENCE_ROW_FILES)" || { printf '%s\n' 'VOLUME_40_GDB_EVIDENCE_ROW_FILES is required' >&2; exit 64; }
	@test -n "$(VOLUME_40_RING_FAMILIES_ROW_FILES)" || { printf '%s\n' 'VOLUME_40_RING_FAMILIES_ROW_FILES is required' >&2; exit 64; }
	@test -n "$(VOLUME_40_SHARED_COMPONENTS_ROW_FILES)" || { printf '%s\n' 'VOLUME_40_SHARED_COMPONENTS_ROW_FILES is required' >&2; exit 64; }
	@test -n "$(VOLUME_40_SHARED_ANCHORS_ROW_FILES)" || { printf '%s\n' 'VOLUME_40_SHARED_ANCHORS_ROW_FILES is required' >&2; exit 64; }
	@for path in $(VOLUME_40_SOURCE_FILES_ROW_FILES) $(VOLUME_40_GDB_EVIDENCE_ROW_FILES) $(VOLUME_40_RING_FAMILIES_ROW_FILES) $(VOLUME_40_SHARED_COMPONENTS_ROW_FILES) $(VOLUME_40_SHARED_ANCHORS_ROW_FILES); do test -s "$$path" || { printf 'required row artifact missing or empty: %s\n' "$$path" >&2; exit 66; }; done
	@test -n "$(VOLUME_40_STRICT_SOURCE_BODY_RECEIPT)" || { printf '%s\n' 'VOLUME_40_STRICT_SOURCE_BODY_RECEIPT is required' >&2; exit 64; }
