"""
Cascading style sheet render engine.

NOT an admitted unary callable. This is an external tool invoked by
the admitted process.py wrapper. It performs multi-step ontology
querying and text generation that cannot be compressed into a single
atomic byte-frame arrow.

Type carriers (primordial):
  - Input  : prim:ByteVector  (turtle ontology from SILMARIL_ONTOLOGY_PATH)
  - Output : prim:ByteVector  (generated CSS written to stdout)
  - Effect : prim:IOException ∪ prim:SPARQLSyntaxError
"""

import os

from config.constants.morphism.user.interface.constructor.cascading.style.sheet.render.format.value import VALUE as _FORMAT
from config.gate.external.python.resource_description_framework_library.graph.library import DEPENDENCY as _GRAPH


def MAIN() -> int:
    ontology_path = os.environ.get("SILMARIL_ONTOLOGY_PATH", "basicttl/ui_constructor.ttl")

    g = _GRAPH()
    g.parse(ontology_path, format=_FORMAT.decode())

    NS = "urn:silmaril:entity#"
    SH = "http://www.w3.org/ns/shacl#"
    RDFS = "http://www.w3.org/2000/01/rdf-schema#"

    out = []
    out.append("/* Generated by silmaril.sparky.morphism.user.interface.constructor.cascading.style.sheet.render.engine */")
    out.append("/* Source: basicttl/ui_constructor.ttl */")
    out.append("")

    # Extract status badge colors
    for status in ["pass", "fail", "warn"]:
        for prop in ["bg", "fg", "border"]:
            q = f"""
                PREFIX silm: <urn:silmaril:entity#>
                SELECT ?value WHERE {{
                    ?s a silm:StatusBadgeColor ;
                       silm:appliesToStatus "{status}" ;
                       silm:colorProperty "{prop}" ;
                       silm:cssValue ?value .
                }}
            """
            for row in g.query(q):
                val = str(row.value)
                if prop == "bg":
                    out.append(f".build-status.{status} {{ background-color: {val}; }}")
                elif prop == "fg":
                    out.append(f".build-status.{status} {{ color: {val}; }}")
                elif prop == "border":
                    out.append(f".build-status.{status} {{ border: 1px solid {val}; }}")

    # Extract base style rules from StyleRule instances
    q = """
        PREFIX silm: <urn:silmaril:entity#>
        SELECT ?selector ?prop ?val WHERE {
            ?rule a silm:StyleRule .
            ?rule silm:selector ?selector .
            ?rule silm:declaration ?decl .
            ?decl silm:property ?prop .
            ?decl silm:value ?val .
        }
    """
    rules = {}
    for row in g.query(q):
        sel = str(row.selector)
        prop = str(row.prop)
        val = str(row.val)
        if sel not in rules:
            rules[sel] = []
        rules[sel].append(f"  {prop}: {val};")

    for sel, decls in rules.items():
        out.append(f"{sel} {{")
        out.extend(decls)
        out.append("}")

    print("\n".join(out))
    return 0


raise SystemExit(MAIN())
