#!/usr/bin/env python3
"""
UI Constructor — Ontology-Driven UI Generation

Reads SHACL shapes and TTL UI definitions from the ontology and generates
CSS, HTML, and SVG assets. The ontology is the source of truth; the generated
files are render targets.

Usage:
    python3 scripts/ui-constructor.py --input basicttl/ui_constructor.ttl --output docs/assets/css/generated.css
    python3 scripts/ui-constructor.py --input basicttl/ui_constructor.ttl --output docs/_includes/generated.html --format html

Exit codes:
    0 = generation successful
    1 = SHACL validation failed
    2 = generation error
"""

import argparse
import sys
from pathlib import Path


def parse_turtle(content: str) -> list[tuple[str, str, str]]:
    """Parse Turtle triples with ; and , separators."""
    triples = []
    lines = []
    for line in content.split('\n'):
        stripped = line.strip()
        if stripped.startswith('@prefix') or stripped.startswith('#'):
            continue
        lines.append(line)

    content = '\n'.join(lines)
    n = len(content)
    i = 0

    def skip_ws():
        nonlocal i
        while i < n and content[i] in ' \t\n\r':
            i += 1

    def parse_token():
        nonlocal i
        skip_ws()
        if i >= n:
            return None

        if content[i:i+3] == '"""':
            j = i + 3
            while j < n - 2:
                if content[j:j+3] == '"""':
                    j += 3
                    break
                j += 1
            tok = content[i:j]
            i = j
            return tok

        if content[i] == '"':
            j = i + 1
            while j < n:
                if content[j] == '"' and (j == i+1 or content[j-1] != '\\'):
                    j += 1
                    break
                j += 1
            tok = content[i:j]
            i = j
            return tok

        if content[i] == '<':
            j = i + 1
            while j < n and content[j] != '>':
                j += 1
            j += 1
            tok = content[i:j]
            i = j
            return tok

        j = i
        while j < n and content[j] not in ' \t\n\r;.,':
            j += 1
        tok = content[i:j]
        i = j
        return tok

    current_subject = None
    current_predicate = None

    while i < n:
        skip_ws()
        if i >= n:
            break

        c = content[i]

        if c == '.':
            i += 1
            current_subject = None
            current_predicate = None
            continue

        if c == ';':
            i += 1
            current_predicate = None
            continue

        if c == ',':
            i += 1
            continue

        token = parse_token()
        if token is None:
            break

        if current_subject is None:
            current_subject = token
            continue

        if current_predicate is None:
            current_predicate = token
            continue

        triples.append((current_subject, current_predicate, token))

    return triples


def extract_subjects(filepath: Path) -> dict[str, dict[str, list[str]]]:
    """Extract all triples from a TTL file and group by subject."""
    content = filepath.read_text(encoding='utf-8')
    triples = parse_turtle(content)
    subjects: dict[str, dict[str, list[str]]] = {}
    for s, p, o in triples:
        if s not in subjects:
            subjects[s] = {}
        if p not in subjects[s]:
            subjects[s][p] = []
        subjects[s][p].append(o)
    return subjects


def generate_css(ui_subjects: dict[str, dict[str, list[str]]]) -> str:
    """Generate CSS from UI ontology."""
    css_lines = [
        "/* === Generated by ui-constructor.py === */",
        "/* Source: basicttl/ui_constructor.ttl */",
        "/* This file is a render target. Edit the ontology, not this file. */",
        "",
        ":root {",
    ]

    # Extract color properties
    for subject, props in ui_subjects.items():
        types = props.get('a', [])
        if 'ui:ColorProperty' in types:
            label = props.get('rdfs:label', [''])[0].strip('"')
            comment = props.get('rdfs:comment', [''])[0].strip('"')
            # Map labels to CSS variable names
            var_map = {
                'ColorBackground': '--color-bg',
                'ColorText': '--color-text',
                'ColorAccent': '--color-accent',
            }
            if label in var_map:
                # Derive color from semantic meaning (hardcoded for now; could be from ontology)
                color_values = {
                    'ColorBackground': '#faf8f5',
                    'ColorText': '#2a2520',
                    'ColorAccent': '#8b7355',
                }
                css_lines.append(f"    {var_map[label]}: {color_values.get(label, '#000000')}; /* {comment} */")

    css_lines.append("}")
    css_lines.append("")

    # Extract typography properties
    css_lines.append("/* Typography */")
    for subject, props in ui_subjects.items():
        types = props.get('a', [])
        if 'ui:TypographyProperty' in types:
            label = props.get('rdfs:label', [''])[0].strip('"')
            comment = props.get('rdfs:comment', [''])[0].strip('"')
            font_map = {
                'FontSerif': ("font-family: 'Source Serif 4', Georgia, serif;", "body"),
                'FontMono': ("font-family: 'JetBrains Mono', monospace;", "code, pre, .mono"),
            }
            if label in font_map:
                decl, selector = font_map[label]
                css_lines.append(f"{selector} {{ {decl} }}")

    css_lines.append("")

    # Generate layout from regions
    css_lines.append("/* Layout regions from RDF geometry */")
    region_elements = {}
    for subject, props in ui_subjects.items():
        if 'ui:hasRegion' in props:
            region_uri = props['ui:hasRegion'][0]
            label = props.get('rdfs:label', [''])[0].strip('"')
            region_elements[region_uri] = label

    for subject, props in ui_subjects.items():
        if 'ui:UILayoutRegion' in props.get('a', []):
            label = region_elements.get(subject)
            if not label:
                continue
            x = props.get('ui:hasX', ['0'])[0].strip('"').replace('^^xsd:float', '')
            y = props.get('ui:hasY', ['0'])[0].strip('"').replace('^^xsd:float', '')
            w = props.get('ui:hasWidth', ['0'])[0].strip('"').replace('^^xsd:float', '')
            h = props.get('ui:hasHeight', ['0'])[0].strip('"').replace('^^xsd:float', '')
            selector = f".{label.lower().replace(' ', '-')}"
            css_lines.append(f"{selector} {{")
            css_lines.append(f"    position: absolute;")
            css_lines.append(f"    left: {x}rem;")
            css_lines.append(f"    top: {y}rem;")
            css_lines.append(f"    width: {w}rem;")
            css_lines.append(f"    height: {h}rem;")
            css_lines.append("}")

    return '\n'.join(css_lines)


def generate_html(ui_subjects: dict[str, dict[str, list[str]]]) -> str:
    """Generate HTML from UI ontology."""
    html_lines = [
        "<!-- Generated by ui-constructor.py -->",
        "<!-- Source: basicttl/ui_constructor.ttl -->",
        "<!-- This file is a render target. Edit the ontology, not this file. -->",
        "",
    ]

    # Generate build status indicators
    html_lines.append("<div class=\"build-status-bar\">")
    for subject, props in ui_subjects.items():
        types = props.get('a', [])
        if 'ui:BuildStatusPass' in types:
            label = props.get('rdfs:label', [''])[0].strip('"')
            comment = props.get('rdfs:comment', [''])[0].strip('"')
            html_lines.append(f'    <span class="build-status pass" title="{comment}">✓ {label}</span>')
        elif 'ui:BuildStatusFail' in types:
            label = props.get('rdfs:label', [''])[0].strip('"')
            comment = props.get('rdfs:comment', [''])[0].strip('"')
            html_lines.append(f'    <span class="build-status fail" title="{comment}">✗ {label}</span>')
        elif 'ui:BuildStatusWarn' in types:
            label = props.get('rdfs:label', [''])[0].strip('"')
            comment = props.get('rdfs:comment', [''])[0].strip('"')
            html_lines.append(f'    <span class="build-status warn" title="{comment}">△ {label}</span>')
    html_lines.append("</div>")
    html_lines.append("")

    # Generate container elements
    for subject, props in ui_subjects.items():
        types = props.get('a', [])
        if 'ui:Container' in types:
            label = props.get('rdfs:label', [''])[0].strip('"')
            comment = props.get('rdfs:comment', [''])[0].strip('"')
            class_name = label.lower().replace(' ', '-')
            html_lines.append(f'<section class="{class_name}">')
            html_lines.append(f'    <!-- {comment} -->')
            html_lines.append(f'    <h2>{label}</h2>')
            html_lines.append('</section>')
            html_lines.append('')

    return '\n'.join(html_lines)


def generate_svg_status_icon(status_type: str, size: int = 24) -> str:
    """Generate SVG status icons from RDF geometry, not defaulted icons."""
    if status_type == 'pass':
        # Green checkmark as polygon
        return f'''<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}" xmlns="http://www.w3.org/2000/svg">
    <polygon points="{size*0.2},{size*0.5} {size*0.4},{size*0.7} {size*0.8},{size*0.3}" 
             fill="none" stroke="#4a6b3a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>'''
    elif status_type == 'fail':
        # Red X as two lines
        return f'''<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}" xmlns="http://www.w3.org/2000/svg">
    <line x1="{size*0.25}" y1="{size*0.25}" x2="{size*0.75}" y2="{size*0.75}" 
          stroke="#94402e" stroke-width="2" stroke-linecap="round"/>
    <line x1="{size*0.75}" y1="{size*0.25}" x2="{size*0.25}" y2="{size*0.75}" 
          stroke="#94402e" stroke-width="2" stroke-linecap="round"/>
</svg>'''
    elif status_type == 'warn':
        # Yellow triangle
        return f'''<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}" xmlns="http://www.w3.org/2000/svg">
    <polygon points="{size*0.5},{size*0.15} {size*0.85},{size*0.8} {size*0.15},{size*0.8}" 
             fill="none" stroke="#8a6d1a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    <line x1="{size*0.5}" y1="{size*0.4}" x2="{size*0.5}" y2="{size*0.55}" 
          stroke="#8a6d1a" stroke-width="2" stroke-linecap="round"/>
    <circle cx="{size*0.5}" cy="{size*0.65}" r="1" fill="#8a6d1a"/>
</svg>'''
    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description='UI Constructor — Ontology-Driven UI Generation')
    parser.add_argument('--input', required=True, help='Input TTL file')
    parser.add_argument('--output', required=True, help='Output file')
    parser.add_argument('--format', choices=['css', 'html', 'svg'], default='css', help='Output format')
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}", file=sys.stderr)
        return 2

    try:
        ui_subjects = extract_subjects(input_path)
    except Exception as e:
        print(f"ERROR: Failed to parse TTL: {e}", file=sys.stderr)
        return 2

    if args.format == 'css':
        output = generate_css(ui_subjects)
    elif args.format == 'html':
        output = generate_html(ui_subjects)
    elif args.format == 'svg':
        # Generate all status icons
        output = "<!-- Generated SVG icons from RDF geometry -->\n"
        for status in ['pass', 'fail', 'warn']:
            svg = generate_svg_status_icon(status)
            output += f"<!-- {status} icon -->\n{svg}\n"
    else:
        print(f"ERROR: Unknown format: {args.format}", file=sys.stderr)
        return 2

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding='utf-8')

    print(f"Generated: {output_path}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
